### ISSUE TITLE
Parsing logs without fails but graph is incomplete

### ISSUE THREAD

**Issue by Sneak94** [PikCeLL/FFXIVLogParser#2]
Parsing of files and graph being made without any problem but it displays only 16 pulls despite there being more than 200 logged.
Game and logs are in english and there is at least a dot for each phase (TEA) so it detects the boss IDs

**Comment by PikCeLL** [comment]
Thanks for the feedback. Could you maybe provide me with one of those logs that is not parsed properly? Put one in a directory alone and if the tool gives you way less pulls than what's inside, I can look into the file to try and fix the issue with the parsing.

**Comment by PikCeLL** [comment]
I think I might have found the isse while working on the next iteration of this project. The RESET trigger ID changed in 6.2, from 40000010 to 4000000F. I won't fix it for the python version as I'm rewriting the whole thing in JS to make it more accessible, but the fix should be easy enought.

**Comment by PikCeLL** [comment]
I think I might have found the isse while working on the next iteration of this project. The RESET trigger ID changed in 6.2, from 40000010 to 4000000F. I won't fix it for the python version as I'm rewriting the whole thing in JS to make it more accessible, but the fix should be easy enought.
